services:
    - docker

script:
    - ./run_tests

cache:
    directories:
        - $HOME/docker
    timeout: 300

before_cache:
    - >
        if [[ $TRAVIS_TEST_RESULT = 0 ]]; then
            docker images -a --format '{{.Repository}}:{{.Tag}} {{.ID}}'
            mkdir -p $HOME/docker
            docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}'\
            | xargs -n 1 -t sh -c 'test $0 = cloud-connector-wheel:latest ||
                                   test $0 = cloud-connector:latest ||
                                   test $0 = swift-s3-sync:latest ||
                                   test $0 = 1space-keystone:latest &&
                                   docker save $0 | gzip -2 > $HOME/docker/$0.tar.gz'
            ls -1 $HOME/docker \
            | xargs -n 1 -t sh -c 'test $0 != cloud-connector-wheel:latest.tar.gz &&
                                   test $0 != cloud-connector:latest.tar.gz &&
                                   test $0 != swift-s3-sync:latest.tar.gz &&
                                   test $0 != 1space-keystone:latest.tar.gz &&
                                   rm -f $HOME/docker/$0'
        fi

before_install:
    - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
