services:
    - docker

before_install:
    - docker build -t swift-s3-sync test/container
    - container_id=$(mktemp)
    - docker run -d -v `pwd`:/swift-s3-sync swift-s3-sync > "${container_id}"

script:
    - docker exec -it `cat ${container_id}` timeout 30 bash -c 'until echo > /dev/tcp/localhost/8080; do sleep 0.5; done'
    - docker exec -it `cat ${container_id}` timeout 30 bash -c 'until echo > /dev/tcp/localhost/10080; do sleep 0.5; done'
    - docker exec -it `cat ${container_id}` netstat -ptan
    - docker exec -it `cat ${container_id}` /bin/bash -c 'cd /swift-s3-sync; nosetests'
    - docker exec -e DOCKER=true -it `cat ${container_id}` /bin/bash -c 'cd /swift-s3-sync; nosetests test/integration'
    - docker exec -it `cat ${container_id}` /bin/bash -c 'cd /swift-s3-sync; flake8'
