services:
    - docker

script:
    - ./run_tests

cache:
    directories:
        - $HOME/docker

before_cache:
    - >
        docker images -a --format '{{.Repository}}:{{.Tag}} {{.ID}}' &&
        mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
        | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz' &&
        docker images -a --filter='dangling=true' --format '{{.ID}}'| xargs -n 1 -t sh -c 'rm $HOME/docker/$0.tar.gz'

before_install:
    - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
